### ISSUE TITLE
Shovel Knight: Treasure Trove

### ISSUE THREAD

**Issue by throwaway09** [Azure-Agst/switchrpc#10]
### Name of Game:

Shovel Knight: Treasure Trove

### Game Shortcode:

sktt

### App Icon:

https://i.imgur.com/DfXf05q.jpg

### States:

- Don't Display State
- Shovel of Hope
- Plague of Shadows
- Specter of Torment
- King of Cards

**Comment by Azure-Agst** [comment]
This game was added! Simply click on settings in the corner of the app, then select it from the menu, and click update! It should then allow you to choose it in the main window. Thanks for your help!
