### ISSUE TITLE
Golf Story

### ISSUE THREAD

**Issue by throwaway09** [Azure-Agst/switchrpc#11]
### Name of Game:

Golf Story

### Game Shortcode:

glfs

### App Icon:

https://i.imgur.com/IDfgU08.jpg

### States:

- Don't Display State
- Teeing Up
- Hole in One
- Driving Range

**Comment by Azure-Agst** [comment]
This game was added! Simply click on settings in the corner of the app, then select it from the menu, and click update! It should then allow you to choose it in the main window. Thanks for your help!
