### ISSUE TITLE
The Legend of Zelda: Breath of the Wild

### ISSUE THREAD

**Issue by throwaway09** [Azure-Agst/switchrpc#12]
### Name of Game:

The Legend of Zelda: Breath of the Wild

### Game Shortcode:

botw

### App Icon:

https://i.imgur.com/40WUClu.jpg

### States:

- Don't Display State
- Finding Korok Seeds
- Completing Shrines
- Exploring Hyrule

**Comment by Azure-Agst** [comment]
This game was added! Simply click on settings in the corner of the app, then select it from the menu, and click update! It should then allow you to choose it in the main window. Thanks for your help!
