### ISSUE TITLE
Super Mario Odyssey

### ISSUE THREAD

**Issue by throwaway09** [Azure-Agst/switchrpc#13]
### Name of Game:

Super Mario Odyssey

### Game Shortcode:

smo

### App Icon:

https://i.imgur.com/jcCFeVn.jpg

### States:

- Don't Display State
- Finding Moons
- Saving Peach
- Collecting Purple Coins

**Comment by Azure-Agst** [comment]
This game was added! Simply click on settings in the corner of the app, then select it from the menu, and click update! It should then allow you to choose it in the main window. Thanks for your help!
