### ISSUE TITLE
Mario Kart 8 Deluxe

### ISSUE THREAD

**Issue by throwaway09** [Azure-Agst/switchrpc#14]
### Name of Game:

Mario Kart 8 Deluxe

### Game Shortcode:

mk8d

### App Icon:

https://i.imgur.com/OPGKfXv.jpg

### States:

- Don't Display State
- Grand Prix
- Time Trials
- VS Race
- Battle
- Online
- Mario Kart TV

**Comment by Azure-Agst** [comment]
This game was added! Simply click on settings in the corner of the app, then select it from the menu, and click update! It should then allow you to choose it in the main window. Thanks for your help!
