### ISSUE TITLE
Donkey Kong: Tropical Freeze

### ISSUE THREAD

**Issue by throwaway09** [Azure-Agst/switchrpc#15]
### Name of Game:

Donkey Kong: Tropical Freeze

### Game Shortcode:

dktf

### App Icon:

https://i.imgur.com/gm5JBph.jpg

### States:

- Don't Display State
- Going Bananas
- Funky Mode

**Comment by Azure-Agst** [comment]
This game was added! Simply click on settings in the corner of the app, then select it from the menu, and click update! It should then allow you to choose it in the main window. Thanks for your help!
