### ISSUE TITLE
Fortnite

### ISSUE THREAD

**Issue by throwaway09** [Azure-Agst/switchrpc#16]
### Name of Game:

Fortnite

### Game Shortcode:

fort

### App Icon:

https://i.imgur.com/Rr292zC.jpg

### States:

- Don't Display State
- Solo
- Duos
- Squads
- 50v50
- Teams of 20
- Sniper Shootout
- Solid Gold
- Blitz
- High Explosives
- Infinity Gauntlet
- Solo Showdown
- Close Encounters
- Blitz Showdown
- Final Fight
- Playground

**Comment by Azure-Agst** [comment]
This game was added as of release! Simplifying all the states down to the active gamemodes.

Simply click on settings in the corner of the app, then select it from the menu, and click update! It should then allow you to choose it in the main window. Thanks for your help!
