### ISSUE TITLE
Kirby Star Allies

### ISSUE THREAD

**Issue by throwaway09** [Azure-Agst/switchrpc#17]
### Name of Game:

Kirby Star Allies

### Game Shortcode:

krsa

### App Icon:

https://i.imgur.com/h2LeZt0.jpg

### States:

- Don't Display State
- Copying Abilities
- Fighting Bosses
- Teaming Up

**Comment by Azure-Agst** [comment]
This game was added! Simply click on settings in the corner of the app, then select it from the menu, and click update! It should then allow you to choose it in the main window. Thanks for your help!
