### ISSUE TITLE
Fortnite typo

### ISSUE THREAD

**Issue by Thomascoolkid** [Azure-Agst/switchrpc#18]
The l in playgrounds is capatalized, it appears as "in PLaygrounds"

**Comment by Azure-Agst** [comment]
Whoops! Fixed that just now. You'll need to refresh the menu in settings before the settings become apparent.

**Comment by Azure-Agst** [comment]
In fact, congratulations, you just helped me find a bug! If refreshing the list in settings doesn't work, restart the app (either by clicking quit, or right click the tray icon > quit) and then update again. That fixed it for me.

I'll work on releasing another update soon that fixes that problem.
