### ISSUE TITLE
Crash Bandicoot N.Sane Trilogy

### ISSUE THREAD

**Issue by Vinicius256** [Azure-Agst/switchrpc#19]
# Suggestion to Add Game:

Thanks for wanting to help improve SwitchRPC! If you fill out the form below with all the info, I'll add it to the master json as soon as I can. You can replace the bracketed info, as that's just template to show you how to fill out the page.

### Name of Game:

Crash Bandicoot N.Sane Trilogy

### Game Shortcode:

(this is an abbreviation [a-z, A-z, 0-9] that makes it easy to identify the game in code.)

crash

### App Icon:

(Link a png/jpg to the icon for the game that I can add to the Discord API. Otherwise, your game will not have an icon in Discord.)

https://pm1.narvii.com/6779/716e846366a3287c338153a9e916a3d1ff1ea47dv2_hq.jpg

### States:

- Don't Display State [Required]
- Playing Crash 1
- Playing Crash 2
- Playing Crash 3
- Doing time trials
- Looking for gems

**Comment by Azure-Agst** [comment]
Added! Restart the app, open settings, and the game should appear!
