### ISSUE TITLE
Hollow Knight

### ISSUE THREAD

**Issue by Mazey** [Azure-Agst/switchrpc#20]
### Name of Game:

Hollow Knight

### Game Shortcode:

hollowk

### App Icon:

https://cdn02.nintendo-europe.com/media/images/11_square_images/games_18/wii_u_download_software_3/SQ_WiiUDS_HollowKnight.jpg

### States:

- Don't Display State
- Speedrun
- Soul Steel

**Comment by Azure-Agst** [comment]
one sec, i'm working on a hotfix for a few bugs and i'll add it afterwards!

**Comment by Mazey** [comment]
All good! Added most of my games that hadn't been submitted yet -- off to bed now, haha 👋

**Comment by Azure-Agst** [comment]
Done! Enable the game in settings and you'll be able to choose it!
