### ISSUE TITLE
Mario + Rabbids Kingdom Battle

### ISSUE THREAD

**Issue by Mazey** [Azure-Agst/switchrpc#21]
Name of Game:
Mario + Rabbids Kingdom Battle

Game Shortcode:
mrkb

App Icon:
http://cdn01.nintendo-europe.com/media/images/11_square_images/games_18/nintendo_switch_5/SQ_NSwitch_MarioAndRabbidsKingdomBattle_EU_image500w.jpg

States:
Don't Display State

**Comment by Azure-Agst** [comment]
Done! Enable the game in settings and you'll be able to choose it!
