### ISSUE TITLE
Overcooked

### ISSUE THREAD

**Issue by Mazey** [Azure-Agst/switchrpc#23]
Name of Game:
Overcooked Special Edition

Game Shortcode:
overcook

App Icon:
http://cdn01.nintendo-europe.com/media/images/11_square_images/games_18/nintendo_switch_download_software/SQ_NSwitchDS_OvercookedSpecialEdition_image500w.jpg

States:
Don't Display State
Campaign
Versus
The Lost Morsel
The Festive Seasoning

**Comment by Azure-Agst** [comment]
Done! Enable the game in settings and you'll be able to choose it!
