### ISSUE TITLE
Rayman Legends

### ISSUE THREAD

**Issue by Mazey** [Azure-Agst/switchrpc#26]
Name of Game:
Rayman Legends: Definitive Edition

Game Shortcode:
raymanlegends

App Icon:
http://cdn01.nintendo-europe.com/media/images/11_square_images/games_18/nintendo_switch_5/SQ_NSwitch_RaymanLegendsDefinitiveEdition_image500w.jpg

States:
Don't Display State
Kung Foot

**Comment by Azure-Agst** [comment]
Done! Enable the game in settings and you'll be able to choose it!
