### ISSUE TITLE
Enter the Gungeon

### ISSUE THREAD

**Issue by Mazey** [Azure-Agst/switchrpc#29]
Name of Game:
Enter the Gungeon

Game Shortcode:
gungeon

App Icon:
http://cdn01.nintendo-europe.com/media/images/11_square_images/games_18/nintendo_switch_download_software/SQ_NSwitchDS_EnterTheGungeon_image500w.jpg

States:
Don't Display State

**Comment by Azure-Agst** [comment]
Done! Enable the game in settings and you'll be able to choose it!
