### ISSUE TITLE
Anyone know some potential states for FIFA?

### ISSUE THREAD

**Issue by Mazey** [Azure-Agst/switchrpc#31]
Name of Game:
FIFA 18

Game Shortcode:
fifa18

App Icon:
http://cdn01.nintendo-europe.com/media/images/11_square_images/games_18/nintendo_switch_5/SQ_NSwitch_EASportsFifa18~1_image500w.jpg

States:
Don't Display State
Ultimate Team

(I haven't played enough fifa to think of display states; would be cool if someone more familiar could suggest some)

**Comment by Azure-Agst** [comment]
in the current revision of the new master.json, but leaving this open in case anyone wants to help

**Comment by wrathsoffire76** [comment]
- Kick off
- Career mode
- Ultimate Team
- Online - Kick off
- Online - Tournament
- FIFA World Cup - Kick off
- FIFA World Cup - Ultimate Team
- FIFA World Cup - Online tournament

Those are just a few off the top of my head

**Comment by Azure-Agst** [comment]
Thanks @wrathsoffire76! I'm closing, and will add these in the next revision of games.
