### ISSUE TITLE
Celeste

### ISSUE THREAD

**Issue by Mazey** [Azure-Agst/switchrpc#32]
Name of Game:
Celeste

Game Shortcode:
celeste

App Icon:
http://cdn01.nintendo-europe.com/media/images/11_square_images/games_18/nintendo_switch_download_software/SQ_NSwitchDS_Celeste_image500w.jpg

States:
Don't Display State
A-Side
B-Side
C-Side
Speedrun
Collecting strawberries

**Comment by Azure-Agst** [comment]
Done! Enable the game in settings and you'll be able to choose it!
