### ISSUE TITLE
N++

### ISSUE THREAD

**Issue by Mazey** [Azure-Agst/switchrpc#33]
Name of Game:
N++

Game Shortcode:
npp

App Icon:
http://cdn01.nintendo-europe.com/media/images/11_square_images/games_18/nintendo_switch_download_software/SQ_NSwitchDS_NPlusPlus_image500w.jpg

States:
Don't Display State
Speedrun

**Comment by Azure-Agst** [comment]
Done! Enable the game in settings and you'll be able to choose it!
