### ISSUE TITLE
Wizard of Legend

### ISSUE THREAD

**Issue by Mazey** [Azure-Agst/switchrpc#36]
Name of Game:
Wizard of Legend

Game Shortcode:
wizoflegend

App Icon:
http://cdn01.nintendo-europe.com/media/images/11_square_images/games_18/nintendo_switch_download_software/SQ_NSwitchDS_WizardOfLegend_image500w.jpg

States:
Don't Display State
Co-op

**Comment by Azure-Agst** [comment]
Done! Enable the game in settings and you'll be able to choose it!
