### ISSUE TITLE
Isaac

### ISSUE THREAD

**Issue by Mazey** [Azure-Agst/switchrpc#38]
Name of Game:
The Binding of Isaac: Afterbirth++

Game Shortcode:
tboi

App Icon:
http://cdn01.nintendo-europe.com/media/images/11_square_images/games_18/nintendo_switch_download_software/SQ_NSwitchDS_TheBindingOfIsaacAfterbirthPlus_image500w.jpg

States:
Don't Display State
Hard
Greed mode

**Comment by Azure-Agst** [comment]
Done! Enable the game in settings and you'll be able to choose it!
