### ISSUE TITLE
Ys VIII: Lacrimosa Of DANA

### ISSUE THREAD

**Issue by Montegro** [Azure-Agst/switchrpc#39]
# Suggestion to Add Game:

Thanks for wanting to help improve SwitchRPC! If you fill out the form below with all the info, I'll add it to the master json as soon as I can. You can replace the placeholder info, as that's just template to show you how to fill out the page.

**I ask you bear with me, as I have to do all of these manually. It may take a while before I can add your game. If it takes too long, feel free to ping me on [Twitter](https://twitter.com/Azure_Agst) or PM me on [Reddit](https://www.reddit.com/user/Azure_Agst/). Or make a PR. Thanks in advance!**

### Name of Game:

Ys VIII: Lacrimoda Of DANA

### Game Shortcode:

(this is an abbreviation [a-z, A-z, 0-9] that makes it easy to identify the game in code.)

ys8

### App Icon:

(Link a png/jpg to the icon for the game that I can add to the Discord API. Otherwise, your game will not have an icon in Discord.)

http://www.nat-games.de/wp-content/uploads/2017/04/nat_games_YS_VIII-1280x720.jpg

### States:

- Don't Display State [Required]

**Comment by Azure-Agst** [comment]
Done! If you're on 2.0.1, restart the app before entering settings to see the game. If you're on 2.0.2, just enter settings, and you'll be set!
