### ISSUE TITLE
Wolfenstein 2: The New Colossus

### ISSUE THREAD

**Issue by TheDogHog** [Azure-Agst/switchrpc#40]
# Suggestion to Add Game:

Thanks for wanting to help improve SwitchRPC! If you fill out the form below with all the info, I'll add it to the master json as soon as I can. You can replace the placeholder info, as that's just template to show you how to fill out the page.

**I ask you bear with me, as I have to do all of these manually. It may take a while before I can add your game. If it takes too long, feel free to ping me on [Twitter](https://twitter.com/Azure_Agst) or PM me on [Reddit](https://www.reddit.com/user/Azure_Agst/). Or make a PR. Thanks in advance!**

### Name of Game:

Wolfenstein 2: The New Colossus

### Game Shortcode:

WLF2
(this is an abbreviation [a-z, A-z, 0-9] that makes it easy to identify the game in code.)

### App Icon:

(Link a png/jpg to the icon for the game that I can add to the Discord API. Otherwise, your game will not have an icon in Discord.)

https://i.imgur.com/uc33Y8I.png

### States:

- Don't Display State [Required]
- Fighting Nazis
- Recouping in the Hub

**Comment by Azure-Agst** [comment]
Done! If you're on 2.0.1, restart the app before entering settings to see the game. If you're on 2.0.2, just enter settings, and you'll be set!
