### ISSUE TITLE
West of Loathing

### ISSUE THREAD

**Issue by mushroomstewart** [Azure-Agst/switchrpc#41]
### Name of Game:

West of Loathing

### Game Shortcode:

wol

### App Icon:

https://d1u5p3l4wpay3k.cloudfront.net/westofloathing_gamepedia_en/thumb/c/c9/Logo.png/250px-Logo.png

### States:

- Don't Display State [Required]
- Walking Stupidly
- Doing Stupid Sidequests
- Fighting Reanimated Skeletons
- Cowering from Pyroboves
- Tinkering with El Vibrato Tech
- Wandering Aimlessly
- Trading with Wanderin' Sally

**Comment by Azure-Agst** [comment]
Done! If you're on 2.0.1, restart the app before entering settings to see the game. If you're on 2.0.2, just enter settings, and you'll be set!
