### ISSUE TITLE
Fast RMX

### ISSUE THREAD

**Issue by TetraVisum** [Azure-Agst/switchrpc#45]
### Name of Game:

Fast RMX

### Game Shortcode:

FastRMX

### App Icon:

https://i.imgur.com/CDKnixa.jpg

### States:

- Don't Display State
- Online Multiplayer
- Singleplayer

**Comment by Azure-Agst** [comment]
Done! If you're on 2.0.1, restart the app before entering settings to see the game. If you're on 2.0.2, just enter settings, and you'll be set!
