### ISSUE TITLE
Dragon Ball Xenoverse 2

### ISSUE THREAD

**Issue by Rokutiz** [Azure-Agst/switchrpc#48]
Thanks for wanting to help improve SwitchRPC! If you fill out the form below with all the info, I'll add it to the master json as soon as I can. You can replace the bracketed info, as that's just template to show you how to fill out the page.

Name of Game:
Dragon Ball Xenoverse 2

Game Shortcode:
(this is an abbreviation [a-z, A-z, 0-9] that makes it easy to identify the game in code.)

DBX2

App Icon:
(Link a png/jpg to the icon for the game that I can add to the Discord API. Otherwise, your game will not have an icon in Discord.)

https://www.google.lt/search?q=dragon+ball+xenoverse+2&rlz=1C1GCEA_enLT797LT797&source=lnms&tbm=isch&sa=X&ved=0ahUKEwiLjLvz143cAhUuiaYKHVAMC3UQ_AUICigB&biw=1920&bih=938#imgrc=2SqRATVz7bWR7M:

States:
Don't Display State [Required]
In Lobby
Doing PQ

**Comment by Azure-Agst** [comment]
Added! You can add it to your app by going into settings and selecting!
