### ISSUE TITLE
OPUS: The Day We Found Earth

### ISSUE THREAD

**Issue by TheLastZombie** [Azure-Agst/switchrpc#50]
### Name of Game:

OPUS: The Day We Found Earth

### Game Shortcode:

opus

### App Icon:

https://cdn03.nintendo-europe.com/media/images/11_square_images/games_18/nintendo_switch_download_software/SQ_NSwitchDS_OpusTheDayWeFoundEarth.jpg

### States:

- Don't Display State

**Comment by Azure-Agst** [comment]
Added! You can add it to your app by going into settings and selecting!
