### ISSUE TITLE
Binaries

### ISSUE THREAD

**Issue by TheLastZombie** [Azure-Agst/switchrpc#51]
### Name of Game:

Binaries

### Game Shortcode:

binaries

### App Icon:

https://cdn02.nintendo-europe.com/media/images/11_square_images/games_18/nintendo_switch_download_software/SQ_NSwitchDS_Binaries.jpg

### States:

- Don't Display State

**Comment by Azure-Agst** [comment]
Added! You can add it to your app by going into settings and selecting!
