### ISSUE TITLE
KAMIKO

### ISSUE THREAD

**Issue by TheLastZombie** [Azure-Agst/switchrpc#52]
### Name of Game:

KAMIKO

### Game Shortcode:

kamiko

### App Icon:

https://cdn03.nintendo-europe.com/media/images/11_square_images/games_18/nintendo_switch_download_software/SQ_NSwitchDS_Kamiko.jpg

### States:

- Don't Display State
- Playing as Yamato
- Playing as Uzume
- Playing as Hinome

**Comment by Azure-Agst** [comment]
Added! You can add it to your app by going into settings and selecting!
