### ISSUE TITLE
VVVVVV

### ISSUE THREAD

**Issue by TheLastZombie** [Azure-Agst/switchrpc#53]
### Name of Game:

VVVVVV

### Game Shortcode:

vvvvvv

### App Icon:

https://cdn03.nintendo-europe.com/media/images/11_square_images/games_18/nintendo_switch_download_software/SQ_NSwitchDS_VVVVVV.jpg

### States:

- Don't Display State
- Main Story
- Time Trials
- Intermissions
- No-Death Mode
- Flip Mode

**Comment by Azure-Agst** [comment]
Added! You can add it to your app by going into settings and selecting!
