### ISSUE TITLE
"Dude the list hasnt even loaded yet."

### ISSUE THREAD

**Issue by TheLastZombie** [Azure-Agst/switchrpc#55]
### Description:

I can't select/choose any games in the Settings window. It just says that the list hasn't loaded even though it has.

![image](https://user-images.githubusercontent.com/8181990/42422858-f6efc00c-82ee-11e8-8bd0-0e1c7460d44a.png)

Running from source works for some reason.

![image](https://user-images.githubusercontent.com/8181990/42422916-44874a6e-82f0-11e8-8c9d-77f61cee76f9.png)

### Steps to Reproduce:

- Launch the Windows build of switchrpc
- Go to settings
- Wait for the list to load (one second at max)
- Select some games
- Click the update button

**Comment by Azure-Agst** [comment]
Hm. This perplexes me actually. The script in question is `app/sub/renderer.js`.

The error pops up when the list, well, hasn't loaded yet. The script starts with a var, "state" set to 1, which signifies it's loading. After the games load, state is set to 0. The error only pops if you select submit while the state is not set to 0. When it should be?

I think that may have been an isolated error. Try reinstalling, waiting for the list to load, count to 5, and then submit.

**Comment by TheLastZombie** [comment]
That did in fact fix it. I guess I'll just close this then. Weird.
