### ISSUE TITLE
Bayonetta 2

### ISSUE THREAD

**Issue by zingiberaceae** [Azure-Agst/switchrpc#56]
# Suggestion to Add Game:

Thanks for wanting to help improve SwitchRPC! If you fill out the form below with all the info, I'll add it to the master json as soon as I can. You can replace the placeholder info, as that's just template to show you how to fill out the page.

**I ask you bear with me, as I have to do all of these manually. It may take a while before I can add your game. If it takes too long, feel free to ping me on [Twitter](https://twitter.com/Azure_Agst) or PM me on [Reddit](https://www.reddit.com/user/Azure_Agst/). Or make a PR. Thanks in advance!**

### Name of Game:

Bayonetta 2

### Game Shortcode:

(this is an abbreviation [a-z, A-z, 0-9] that makes it easy to identify the game in code.)

bayonetta2

### App Icon:

(Link a png/jpg to the icon for the game that I can add to the Discord API. Otherwise, your game will not have an icon in Discord.)

https://www.heypoorplayer.com/wp-content/uploads/2018/04/Bayonetta-2-Banner-2.jpg

### States:

- Don't Display State [Required]
- 1st Climax
- 2nd Climax
- 3rd Climax
- ∞ Climax
- Tag Climax

**Comment by Azure-Agst** [comment]
Added!

- 2.0.1 - Restart the app, go into settings and enjoy!
- 2.0.2 - No restart needed! Just enter settings and enjoy!
