### ISSUE TITLE
ARMS

### ISSUE THREAD

**Issue by Thomascoolkid** [Azure-Agst/switchrpc#6]
### Name of Game:

ARMS

### Game Shortcode:

arms

### App Icon:

https://i.imgur.com/ard5ZJW.png

### States:

- Don't Display State
- Grand Prix
- Party Crash
- Ranked Match
- Training
- 1-on-100
- V-Ball
- Hoops
- Skillshot
- Hedlok Scramble

**Comment by throwaway09** [comment]
Here's the official icon, if you'd like:

https://i.imgur.com/Hobw0DU.jpg

**Comment by Azure-Agst** [comment]
for the record, i'm currently working on all your requests right now! should be live in a sec, i'll keep you posted.

**Comment by Azure-Agst** [comment]
This game was added! Simply click on settings in the corner of the app, then select it from the menu, and click update! It should then allow you to choose it in the main window. Thanks for your help!
