### ISSUE TITLE
Hollow Knight

### ISSUE THREAD

**Issue by robotzurg** [Azure-Agst/switchrpc#60]
# Suggestion to Add Game:

Thanks for wanting to help improve SwitchRPC! If you fill out the form below with all the info, I'll add it to the master json as soon as I can. You can replace the placeholder info, as that's just template to show you how to fill out the page.

**I ask you bear with me, as I have to do all of these manually. It may take a while before I can add your game. If it takes too long, feel free to ping me on [Twitter](https://twitter.com/Azure_Agst) or PM me on [Reddit](https://www.reddit.com/user/Azure_Agst/). Or make a PR. Thanks in advance!**

### Name of Game:

Hollow Knight

### Game Shortcode:

(this is an abbreviation [a-z, A-z, 0-9] that makes it easy to identify the game in code.)

HK

### App Icon:

(Link a png/jpg to the icon for the game that I can add to the Discord API. Otherwise, your game will not have an icon in Discord.)

https://media.nintendo.com/nintendo/bin/1_5p76bqyTV2lXo9HAAkEdxtXGFCkanr/POZuyZfpU9WsxLfLbk7kmgDk4JLn-_P5.png

### States:

- Don't Display State [Required]
- Exploring Hallownest

**Comment by Azure-Agst** [comment]
Closing, as this game is already in the list. It's right in between Picross and Enter the Gungeon. :)
