### ISSUE TITLE
Doesn't work on Linux (Cannot read property 'write' of null)

### ISSUE THREAD

**Issue by Josephvb10** [Azure-Agst/switchrpc#62]
### Description:

Using the AppImage executable I get the following errors:

```
(node:4156) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Could not connect
(node:4156) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
{ appiconid: 'home',
  gamename: 'Home Menu',
  gamestate: 'Just Looking Around' }
(node:4156) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): TypeError: Cannot read property 'write' of null
{ Error [RPC_CONNECTION_TIMEOUT]
    at Timeout.setTimeout (/tmp/.mount_switchEIqkXn/resources/app.asar/node_modules/discord-rpc/src/Client.js:110:47)
    at ontimeout (timers.js:475:11)
    at Timer.unrefdHandle (timers.js:588:5) [Symbol(code)]: 'RPC_CONNECTION_TIMEOUT' }
```

`### Steps to Reproduce:

Just launch Discord and then the AppImage

**Comment by Josephvb10** [comment]
I found the problem, apparently this doesn't work with the snapd version of Discord. Installed the normal one and everything works fine.

**Comment by Azure-Agst** [comment]
Yeah, unhandled promise rejections usually fall under discord's list of problems. It means RPC isn't accepting the data, either because something else is showing rich presence, or a bug in their sw, which is of no fault of switchrpc.

I will note this, however. Thanks for your help! :)
