### ISSUE TITLE
Fire Emblem Warriors (long version - didn't see the other poster)

### ISSUE THREAD

**Issue by minininny** [Azure-Agst/switchrpc#65]
Edit: I didn't initially see that other person's post! But here's a longer, more specific iteration.

# Suggestion to Add Game:

### Name of Game: 

Fire Emblem Warriors

### Game Shortcode:

FEW

### App Icon:

https://media.nintendo.com/nintendo/bin/7-7gLOCf488L-q4f52r_qs1XNByW-oVI/5wzwZLfhwzpI_yRCm1YYXS1hbbsY_deQ.jpg

### States:

- Don't Display State [Required]
- Story Mode
- Free Mode
- History Mode: Invisible Ties
- History Mode: The Path is Yours
- History Mode: The Dark Pontifex
- History Mode: Noble Lady of Caelin
- History Mode: Together to the End
- History Mode [DLC]: Hero Challenge
- History Mode [DLC]: Grief
- History Mode [DLC]: Land of Gods
- History Mode [DLC]: Cold Reception
- History Mode [DLC]: A Brush in the Teeth
- History Mode [DLC]: Princess Minerva
- History Mode [DLC]: Knorda Market
- History Mode [DLC]: Scion of Legend
- History Mode [DLC]: Emmeryn
- History Mode [DLC]: Caravan Dancer
- Grinding for supports
- Farming for materials
- Hunting for Anna

**Comment by Charzard4261** [comment]
Aha! This is a much more detailed version than mine! I'll close mine.

**Comment by Azure-Agst** [comment]
Woops! Sorry about the wait, life happened there for a bit and this fell to the wayside.

I've added your game to the list and you should see it in settings. I'm working on adding the icon to discord right now. You should be able to choose the game from the settings menu. Thanks!
