### ISSUE TITLE
Sushi Striker: The Way of Sushido

### ISSUE THREAD

**Issue by minininny** [Azure-Agst/switchrpc#66]
# Suggestion to Add Game:

### Name of Game: 

Sushi Striker: The Way of Sushido

### Game Shortcode:

sushi

### App Icon:

https://upload.wikimedia.org/wikipedia/en/9/9f/Sushi_Striker_The_Way_of_Sushido_cover_art.jpg

### States:

- Don't Display State [Required]
- Eating sushi
- Recruiting sushi sprites
- Defeating the Empire
- Online Tasteful Battles
- Online Chaos Battles

**Comment by Azure-Agst** [comment]
Woops! Sorry about the wait, life happened there for a bit and this fell to the wayside.

I've added your game to the list and you should see it in settings. I'm working on adding the icon to discord right now. You should be able to choose the game from the settings menu. Thanks!
