### ISSUE TITLE
Game Suggestion: L.A Noire

### ISSUE THREAD

**Issue by MountPeter** [Azure-Agst/switchrpc#67]
### Name of Game:

L.A Noire

### Game Shortcode:

(this is an abbreviation [a-z, A-z, 0-9] that makes it easy to identify the game in code.)

lanoir

### App Icon:

![image](https://user-images.githubusercontent.com/41084543/42532940-01946f6e-8491-11e8-833f-68025efa9df1.png)

### States:

- Don't Display State [Required]
- Investigating
- Cruising around

**Comment by Azure-Agst** [comment]
Woops! Sorry about the wait, life happened there for a bit and this fell to the wayside.

I've added your game to the list and you should see it in settings. I'm working on adding the icon to discord right now. You should be able to choose the game from the settings menu. Thanks!
