### ISSUE TITLE
Pokken Tournament DX

### ISSUE THREAD

**Issue by Smethan** [Azure-Agst/switchrpc#68]
# Suggestion to Add Game:

Thanks for wanting to help improve SwitchRPC! If you fill out the form below with all the info, I'll add it to the master json as soon as I can. You can replace the placeholder info, as that's just template to show you how to fill out the page.

**I ask you bear with me, as I have to do all of these manually. It may take a while before I can add your game. If it takes too long, feel free to ping me on [Twitter](https://twitter.com/Azure_Agst) or PM me on [Reddit](https://www.reddit.com/user/Azure_Agst/). Or make a PR. Thanks in advance!**

### Name of Game:

Pokken Tournament DX

### Game Shortcode:

(this is an abbreviation [a-z, A-z, 0-9] that makes it easy to identify the game in code.)

pkdx

### App Icon:

(Link a png/jpg to the icon for the game that I can add to the Discord API. Otherwise, your game will not have an icon in Discord.)

http://media.comicbook.com/2017/09/pokken-tournament-1021329.png

### States:

- Don't Display State [Required]
- Solo Campaign
- Local Matches
- Online Matches
- Practice Mode

**Comment by Azure-Agst** [comment]
Woops! Sorry about the wait, life happened there for a bit and this fell to the wayside.

I've added your game to the list and you should see it in settings. I'm working on adding the icon to discord right now. You should be able to choose the game from the settings menu. Thanks!
