### ISSUE TITLE
New Game: Octopath Traveler

### ISSUE THREAD

**Issue by wfournier** [Azure-Agst/switchrpc#69]
### Name of Game:

Octopath Traveler

### Game Shortcode:

OCTO

### App Icon:

https://doochydgamingdotcom.files.wordpress.com/2018/07/octopath_traveler_for_switch_1-e1530805248269.jpg

### States:

- Don't Display State [Required]
- Questing
- Hunting monsters
- Grinding
- Playing as Ophilia
- Playing as Cyrus
- Playing as Tressa
- Playing as Olberic
- Playing as Primrose
- Playing as Alfyn
- Playing as Therion
- Playing as H'aanit

**Comment by Azure-Agst** [comment]
Woops! Sorry about the wait, life happened there for a bit and this fell to the wayside.

I've added your game to the list and you should see it in settings. I'm working on adding the icon to discord right now. You should be able to choose the game from the settings menu. Thanks!
