### ISSUE TITLE
Snipperclips

### ISSUE THREAD

**Issue by Thomascoolkid** [Azure-Agst/switchrpc#7]
### Name of Game:

Snipperclips

### Game Shortcode:

snip

### App Icon:

https://i.imgur.com/SR7KCsA.jpg

### States:

- Don't Display State [Required]
- Noisy Notebook
- Retro Reboot
- Silly Science

**Comment by Azure-Agst** [comment]
This game was added! Simply click on settings in the corner of the app, then select it from the menu, and click update! It should then allow you to choose it in the main window. Thanks for your help!
