### ISSUE TITLE
New Game Shantae and the Pirate's Curse

### ISSUE THREAD

**Issue by billygijoe** [Azure-Agst/switchrpc#70]
### Name of Game:
Shantae and the Pirate's Curse

### Game Shortcode:
satpc

### App Icon:
![Game Icon](https://i.imgur.com/H3UcgTP.png)

### States:

- Don't Display State [Required]
- Grinding 'Super Shantae Nab'

**Comment by Azure-Agst** [comment]
Woops! Sorry about the wait, life happened there for a bit and this fell to the wayside.

I've added your game to the list and you should see it in settings. I'm working on adding the icon to discord right now. You should be able to choose the game from the settings menu. Thanks!
