### ISSUE TITLE
Fate Extella

### ISSUE THREAD

**Issue by KilimIG** [Azure-Agst/switchrpc#73]
### Name of Game:

Fate/Extella: The Umbral Star

### Game Shortcode:

fext

### App Icon:

https://kil.im/u/Wwh.png

### States:

- Don't Display State [Required]

**Comment by Azure-Agst** [comment]
Woops! Sorry about the wait, life happened there for a bit and this fell to the wayside.

I've added your game to the list and you should see it in settings. I'm working on adding the icon to discord right now. You should be able to choose the game from the settings menu. Thanks!
