### ISSUE TITLE
Suggestion: The Elder Scrolls V: Skyrim

### ISSUE THREAD

**Issue by MountPeter** [Azure-Agst/switchrpc#78]
### Name of Game:

The Elder Scrolls V: Skyrim

### Game Shortcode:

(this is an abbreviation [a-z, A-z, 0-9] that makes it easy to identify the game in code.)

skyrim

### App Icon:
![image](https://user-images.githubusercontent.com/41084543/42721614-5d7aed46-8746-11e8-8b08-3f60940d32e1.png)

### States:

- Don't Display State [Required]
- Fighting a dragon
- Helping citizen
- Looting a dungeon
- Building a house

**Comment by Azure-Agst** [comment]
Honestly I could have sworn I had added this already, but apparently not! I'm on it!

**Comment by Azure-Agst** [comment]
Added! Restart your app to see the game pop up in settings!
