### ISSUE TITLE
Shining Resonance Refrain

### ISSUE THREAD

**Issue by KilimIG** [Azure-Agst/switchrpc#79]
### Name of Game:

Shining Resonance Refrain

### Game Shortcode:

srr

### App Icon:

https://www.psu.com/app/uploads/2018/07/Shining_Resonance-768x640.jpg

### States:

- Don't Display State [Required]
- Original Mode
- Refrain Mode

**Comment by Azure-Agst** [comment]
Added! Restart your app to see the game pop up in settings!
