### ISSUE TITLE
Hyrule Warriors: Definitive Edition

### ISSUE THREAD

**Issue by throwaway09** [Azure-Agst/switchrpc#8]
### Name of Game:

Hyrule Warriors: Definitive Edition

### Game Shortcode:

hwde

### App Icon:

https://i.imgur.com/dpQSRAR.jpg

### States:

- Don't Display State
- Capturing Keeps
- Taking Outposts
- Executing Combos

**Comment by Azure-Agst** [comment]
This game was added! Simply click on settings in the corner of the app, then select it from the menu, and click update! It should then allow you to choose it in the main window. Thanks for your help!
