### ISSUE TITLE
Update the fortnite icon

### ISSUE THREAD

**Issue by Karthik99999** [Azure-Agst/switchrpc#81]
This is not a suggestion to add a game, rather to update the fortnite icon (it's still the season 4 icon). Here is the new icon:
![fortnite-season-5-header](https://user-images.githubusercontent.com/32044378/42737227-a95db1d2-883e-11e8-809b-599ed9e2e50e.jpg)

**Comment by Azure-Agst** [comment]
Noted! Doing that in tonight's revision.

**Comment by Azure-Agst** [comment]
Done!
