### ISSUE TITLE
Add CaveStory+ States

### ISSUE THREAD

**Issue by Llynnbin** [Azure-Agst/switchrpc#83]
### Description:

[Summary of problem here. Be descriptive!]
i noticed that CaveStory+ has no states, having played that game multiple times i thought i could help out
 
**States:**
- Don't Display State [Required]
- Story Mode
- Curly Story
- Jukebox
- Machine Gun Challenge
- Sand Pit
- Sanctuary Time Attack
- Boss Attack
- Wind Fortress
- Nemesis Challenge

**Comment by Azure-Agst** [comment]
added! go to settings to see the changes!
