### ISSUE TITLE
Add Enter The Gungeon States

### ISSUE THREAD

**Issue by Llynnbin** [Azure-Agst/switchrpc#84]
### Description:

[Summary of problem here. Be descriptive!]
Enter The Gungeon also has no states, i'd like to give you some,

**States:**

- Don't Display State [Required]
- In The Gungeon
- Challenge Mode
- Boss Rush
- Chamber 1 - Keep of the Lead Lord
- Chamber 2 - Gungeon Proper
- Chamber 3 - Black Powder Mine
- Chamber 4 - Hollow
- Chamber 5 - Forge
- Chamber 6 - Bullet Hell

**Comment by Azure-Agst** [comment]
added! go to settings to see the changes!
