### ISSUE TITLE
Minecraft

### ISSUE THREAD

**Issue by mrEkli** [Azure-Agst/switchrpc#85]
# Suggestion to Add Game:

Thanks for wanting to help improve SwitchRPC! If you fill out the form below with all the info, I'll add it to the master json as soon as I can. You can replace the placeholder info, as that's just template to show you how to fill out the page.

**I ask you bear with me, as I have to do all of these manually. It may take a while before I can add your game. If it takes too long, feel free to ping me on [Twitter](https://twitter.com/Azure_Agst) or PM me on [Reddit](https://www.reddit.com/user/Azure_Agst/). Or make a PR. Thanks in advance!**

### Name of Game:

Minecraft

### Game Shortcode:

(this is an abbreviation [a-z, A-z, 0-9] that makes it easy to identify the game in code.)

mine

### App Icon:

(Link a png/jpg to the icon for the game that I can add to the Discord API. Otherwise, your game will not have an icon in Discord.)

Not sure where to find the icon but it's based on this image: https://cdn.vox-cdn.com/thumbor/B1LnWbYGJ01Gin2HnRlNqzqZGRA=/0x0:845x480/920x613/filters:focal(356x173:490x307):format(webp)/cdn.vox-cdn.com/uploads/chorus_image/image/59710133/szML_eL4J2dLtZfMS3ccaAmOjWP8qVeR.0.jpg

### States:

- Don't Display State [Required]
- Mining for Resources
- Gathering Resources
- Playing with Animals
- Trading with Villagers
- Creating Works of Art
- Hanging Out Online
- Exploring the World

**Comment by Azure-Agst** [comment]
Closing, because duplicate. You can see the version i'm adding [here](https://github.com/Azure-Agst/switchrpc/issues/77).
