### ISSUE TITLE
DOOM

### ISSUE THREAD

**Issue by throwaway09** [Azure-Agst/switchrpc#9]
### Name of Game:

DOOM

### Game Shortcode:

doom

### App Icon:

https://i.imgur.com/fXqtbCq.jpg

### States:

- Don't Display State
- Slaying Demons
- Harvesting Souls
- Killing for Glory

**Comment by Azure-Agst** [comment]
This game was added! Simply click on settings in the corner of the app, then select it from the menu, and click update! It should then allow you to choose it in the main window. Thanks for your help!
