### ISSUE TITLE
Sonic Mania

### ISSUE THREAD

**Issue by superminer64** [Azure-Agst/switchrpc#90]
# Suggestion to Add Game:

Thanks for wanting to help improve SwitchRPC! If you fill out the form below with all the info, I'll add it to the master json as soon as I can. You can replace the placeholder info, as that's just template to show you how to fill out the page.

**I ask you bear with me, as I have to do all of these manually. It may take a while before I can add your game. If it takes too long, feel free to ping me on [Twitter](https://twitter.com/Azure_Agst) or PM me on [Reddit](https://www.reddit.com/user/Azure_Agst/). Or make a PR. Thanks in advance!**

### Name of Game:

Sonic Mania

### Game Shortcode:

(this is an abbreviation [a-z, A-z, 0-9] that makes it easy to identify the game in code.)

sm

### App Icon:

(Link a png/jpg to the icon for the game that I can add to the Discord API. Otherwise, your game will not have an icon in Discord.)

https://www.google.com/url?sa=i&source=images&cd=&cad=rja&uact=8&ved=2ahUKEwiS0bqBgKzcAhVEXawKHXQiDw0QjRx6BAgBEAU&url=http%3A%2F%2Fsonic.wikia.com%2Fwiki%2FFile%3AMania_Icon.JPG&psig=AOvVaw2M7qVEXDj3-oZB5Xu1TMse&ust=1532118415138666

### States:

- Mania Mode
-Encore Mode
- Time Attack
-Competition
-Blue Spheres
-Mean Bean Machine
-D.A. Garden

**Comment by Azure-Agst** [comment]
Added! Restart your app to see the game pop up in settings!
