### ISSUE TITLE
Game Addition: Sonic Forces

### ISSUE THREAD

**Issue by Chandlier1229** [Azure-Agst/switchrpc#91]
# Suggestion to Add Game:

Thanks for wanting to help improve SwitchRPC! If you fill out the form below with all the info, I'll add it to the master json as soon as I can. You can replace the placeholder info, as that's just template to show you how to fill out the page.

**I ask you bear with me, as I have to do all of these manually. It may take a while before I can add your game. If it takes too long, feel free to ping me on [Twitter](https://twitter.com/Azure_Agst) or PM me on [Reddit](https://www.reddit.com/user/Azure_Agst/). Or make a PR. Thanks in advance!**

### Name of Game:

SONIC FORCES

### Game Shortcode:

(this is an abbreviation [a-z, A-z, 0-9] that makes it easy to identify the game in code.)

SF

### App Icon:

(Link a png/jpg to the icon for the game that I can add to the Discord API. Otherwise, your game will not have an icon in Discord.)

https://vignette.wikia.nocookie.net/sonic/images/d/dc/Sonic_Forces_Speed_Battle_-_Icon_1509622472.png/revision/latest?cb=20171117140613

### States:

- Don't Display State [Required]
- Viewing the World Map
- Playing Episode Shadow
- Playing in a Sonic Stage
- Playing in a Classic Stage
- Playing in an Avatar Stage

**Comment by Azure-Agst** [comment]
added! go to settings to see the changes!

**Comment by Azure-Agst** [comment]
added! go to settings to see the changes!

**Comment by Chandlier1229** [comment]
When I go to see the said changes, Forces is not showing. http://prntscr.com/kcsh2v
