### ISSUE TITLE
A suggestion for another game

### ISSUE THREAD

**Issue by CardboardLuigi** [Azure-Agst/switchrpc#93]
# Suggestion to Add Game:

Thanks for wanting to help improve SwitchRPC! If you fill out the form below with all the info, I'll add it to the master json as soon as I can. You can replace the placeholder info, as that's just template to show you how to fill out the page.

**I ask you bear with me, as I have to do all of these manually. It may take a while before I can add your game. If it takes too long, feel free to ping me on [Twitter](https://twitter.com/Azure_Agst) or PM me on [Reddit](https://www.reddit.com/user/Azure_Agst/). Or make a PR. Thanks in advance!**

### Name of Game:

Sonic Mania Plus

### Game Shortcode:

(this is an abbreviation [a-z, A-z, 0-9] that makes it easy to identify the game in code.)

smp

### App Icon:

(Link a png/jpg to the icon for the game that I can add to the Discord API. Otherwise, your game will not have an icon in Discord.)

https://pre00.deviantart.net/4db0/th/pre/f/2018/079/e/3/sonic_mania_plus_wallpaper_for_ipad_mini_4_v_1_by_artificialgreninja-dc6dca3.png

### States:

- Don't Display State [Required]
- Blasting Through the Mania With Sonic Speed!
- Experiencing the Encore
- In Competition Mode
- Playing Time Trials
- Playing One of the Extra Modes

**Comment by Azure-Agst** [comment]
Closing, because duplicate. You can see the version i'm adding [here](https://github.com/Azure-Agst/switchrpc/issues/90)
