### ISSUE TITLE
Suggestion: Minecraft Bedrock

### ISSUE THREAD

**Issue by ncmoud** [Azure-Agst/switchrpc#94]
# Suggestion to Add Game:

Thanks for wanting to help improve SwitchRPC! If you fill out the form below with all the info, I'll add it to the master json as soon as I can. You can replace the placeholder info, as that's just template to show you how to fill out the page.

**I ask you bear with me, as I have to do all of these manually. It may take a while before I can add your game. If it takes too long, feel free to ping me on [Twitter](https://twitter.com/Azure_Agst) or PM me on [Reddit](https://www.reddit.com/user/Azure_Agst/). Or make a PR. Thanks in advance!**

### Name of Game:

Minecraft for Nintendo Switch

### Game Shortcode:

mcpe

### App Icon:

https://cdn02.nintendo-europe.com/media/images/11_square_images/games_18/nintendo_switch_5/SQ_NSwitch_Minecraft_CMM_big.jpg

### States:

- Don't Display State [Required]
- Playing in Survival
- Playing in Creative
- Playing in a server
- Playing in Realms

**Comment by Azure-Agst** [comment]
Already added! Restart the app to see the game pop up in settings!
